--- 
thesis_title: "A Minimal YSU Thesis Example"
author: "Your Name Here"
thesis_degree:  "Master of Science"
thesis_program: "Mathematics"
thesis_month: "May"
thesis_year:  "20XX"
thesis_advisor: "Thesis Advisor's Name, Degree"
committee_memA: "Committee Member's Name, Degree"
committee_memB: "Committee Member's Name, Degree"
graduate_dean:  "Salvatore A.~Sanders, PhD"
knit: bookdown::render_book
bibliography: [bib/thesis.bib, bib/packages.bib]
# Download your specific csl file and refer to it in the line below.
csl: csl/apa.csl
link-citations: yes
output:
  thesisdown::thesis_pdf: 

# This will automatically install the {remotes} package and {thesisdown}
# Change this to FALSE if you'd like to install them manually on your own.
params:
  'Install needed packages for {thesisdown}': True
---


```{r include_packages, include=FALSE}
# This chunk ensures that the thesisdown package is
# installed and loaded. This thesisdown package includes
# the template files for the thesis.
if (!require(remotes)) {
  if (params$`Install needed packages for {thesisdown}`) {
    install.packages("remotes", repos = "https://cran.rstudio.com")
  } else {
    stop(
      paste('You need to run install.packages("remotes")",
            "first in the Console.')
    )
  }
}
if (!require(thesisdown)) {
  if (params$`Install needed packages for {thesisdown}`) {
    remotes::install_github("ismayc/thesisdown")
  } else {
    stop(
      paste(
        "You need to run",
        'remotes::install_github("ismayc/thesisdown")',
        "first in the Console."
      )
    )
  }
}
library(thesisdown)
# Set how wide the R output will go
options(width = 70)
```



```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown', 'thesisdown'
), 'bib/packages.bib')
```


